In [1]:
import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)
Task3_path = 'C:\\VSC\\JJaemni\\CSV\\Task3\\'
Task4_path = 'C:\\VSC\\JJaemni\\CSV\\Task4\\'

wanted = pd.read_csv(Task3_path + 'wanted.csv')
ds_w = pd.read_csv(Task3_path + 'wanted_3_Requirement.csv')
da_w = pd.read_csv(Task3_path + 'wanted_4_Preference.csv')
de_w = pd.read_csv(Task3_path + 'wanted_5_StackTool.csv')

jobplanet = pd.read_csv(Task4_path + 'jobplanet.csv')
ds_j = pd.read_csv(Task4_path + 'jobplanet_3_Requirement.csv')
da_j = pd.read_csv(Task4_path + 'jobplanet_4_Preference.csv')
de_j = pd.read_csv(Task4_path + 'jobplanet_5_StackTool.csv')

In [2]:
wanted.insert(3, 'Requirement', ds_w)
wanted.insert(4, 'Preference', da_w)
wanted.insert(5, 'StackTool', de_w)
wanted

,Title,Company,Content,Requirement,Preference,StackTool,Link,Location,label
0,[100억↑투자] 데이터사이언티스트,해줌,"해줌은 2012년에 설립된 회사로, 소비자로부터 멀게만 느껴졌던 대한민국 태양광 산...",\n- 관련 업무 경력 3년 이상인 분\n- 시계열 데이터를 분석하여 예측에 대한 ...,\n- 기상관련 데이터 경험\n- 머신러닝 관련 모델링 도구 경험자 (Tensorf...,\nPytorch\nTensorflow\nPython,https://www.wanted.co.kr/wd/147049,서울 · 한국,데이터 사이언티스트
1,데이터 사이언티스트,더블미디어,"더블미디어는 인터넷방송 플랫폼 ""팬더티비""을 서비스중입니다. 빠른 시간안에 국내에서...","\n•웹/앱 서비스 데이터 분석 경력 2년 이상, 혹은 그에 상응하는 업무 능력 보...",\n•통계 분석과 ML 알고리즘 지식과 실무 경험이 있으신 분\n\n•A/B 테스트...,\nKotlin\nSpring Framework,https://www.wanted.co.kr/wd/174955,서울 · 한국,데이터 사이언티스트
2,플랫폼팀 데이터 사이언티스트,와이어드컴퍼니,[와이어드는 사람의 영향력을 가치로 바꿔갈 수 있는 동료를 찾고 있어요.]\n\n\...,\n• 커머스 관련 실무 경험을 2년 이상 가지고 계신 분\n• 데이터 분석 및 머...,\n• 비정형화 된 데이터를 다양한 기술을 활용하여 팀원들에게 유의미한 정보로 만들...,NaN,https://www.wanted.co.kr/wd/97792,서울 · 한국,데이터 사이언티스트
3,Data Scientist(데이터 사이언티스트),프라이데이즈랩(Retentics),폭풍 성장 중인 글로벌 스타트업에서 유저에게 사랑받는 리텐틱스를 만들기 위해 함께 ...,\n[데이터 사이언티스트로 이런 분을 찾아요]\n#자격 요건\n• 3년 이상의 ML...,\n[이런 경험이 있으신 분이면 더 좋아요]\n#우대 사항\n• Data Scien...,NaN,https://www.wanted.co.kr/wd/163313,서울 · 한국,데이터 사이언티스트
4,데이터 사이언티스트,아템드메라키,Algorith는 데이터 및 통계수학적 분석을 통해 디지털 자산 투자 관리 회사입니...,"\n• 최소 데이터 과학, 통계, 컴퓨터 공학 또는 관련 분야의 학사 학위를 보유하...",\n• 석사학위 및 박사학위 (박사과정 지원자) 우대\n• 데이터 분석 또는 유사 ...,NaN,https://www.wanted.co.kr/wd/119383,서울 · 한국,데이터 사이언티스트
...,...,...,...,...,...,...,...,...,...
128,MS-SQL 데이터베이스엔지니어,티디지,TDG는 Microsoft Cloud Solution Partner로서 풍부한 IT...,NaN,NaN,\nAzure\nC / C++\n개발\nSharePoint,https://www.wanted.co.kr/wd/171095,서울 · 한국,데이터 엔지니어
129,공공기관 리눅스엔지니어(서버운영자),비욘드데이터,• 리눅스 엔지니어\n• 서버 운영\n주요업무\n• 서버 운영\n• 백업 & 보안S...,NaN,NaN,\nLinux\nOracle,https://www.wanted.co.kr/wd/171847,경북 · 한국,데이터 엔지니어
130,리눅스엔지니어(중급/상주),비욘드데이터,• 서버 운영\n•\n주요업무\n• 리눅스 서버 관리\n•\n자격요건\n• 리눅스 ...,NaN,NaN,\nLinux\nOracle,https://www.wanted.co.kr/wd/172049,경북 · 한국,데이터 엔지니어
131,"데이터엔지니어링/백엔드 개발자 (Python, Node.js)",코드크레인(CodeCrain),안녕하세요!\n저희 코드크레인은 국내에서 가장 빠르게 성장하고 있는 IT개발/컨설팅...,NaN,NaN,\nMySQL\nPython\nAWS\nNodeJS,https://www.wanted.co.kr/wd/160009,서울 · 한국,데이터 엔지니어
132,[데이터사업] DB엔지니어,인젠트,"우리 모두를 위한 변화, 당신과 가장 가까운 인젠트의 스마트한 기술을 만나보세요.\...",NaN,NaN,\nLinux\n보안\n인프라\n정보 보안\nWindows 서버\n정보관리\nNAS...,https://www.wanted.co.kr/wd/112676,서울 · 한국,데이터 엔지니어

In [3]:
L = []
for i in range(0, wanted.shape[0]):
    a = wanted.Location[i].replace(' · 한국', '')
    L.append(a)

loc_w = pd.DataFrame({'Location': L})
wanted.Location = loc_w
wanted

,Title,Company,Content,Requirement,Preference,StackTool,Link,Location,label
0,[100억↑투자] 데이터사이언티스트,해줌,"해줌은 2012년에 설립된 회사로, 소비자로부터 멀게만 느껴졌던 대한민국 태양광 산...",\n- 관련 업무 경력 3년 이상인 분\n- 시계열 데이터를 분석하여 예측에 대한 ...,\n- 기상관련 데이터 경험\n- 머신러닝 관련 모델링 도구 경험자 (Tensorf...,\nPytorch\nTensorflow\nPython,https://www.wanted.co.kr/wd/147049,서울,데이터 사이언티스트
1,데이터 사이언티스트,더블미디어,"더블미디어는 인터넷방송 플랫폼 ""팬더티비""을 서비스중입니다. 빠른 시간안에 국내에서...","\n•웹/앱 서비스 데이터 분석 경력 2년 이상, 혹은 그에 상응하는 업무 능력 보...",\n•통계 분석과 ML 알고리즘 지식과 실무 경험이 있으신 분\n\n•A/B 테스트...,\nKotlin\nSpring Framework,https://www.wanted.co.kr/wd/174955,서울,데이터 사이언티스트
2,플랫폼팀 데이터 사이언티스트,와이어드컴퍼니,[와이어드는 사람의 영향력을 가치로 바꿔갈 수 있는 동료를 찾고 있어요.]\n\n\...,\n• 커머스 관련 실무 경험을 2년 이상 가지고 계신 분\n• 데이터 분석 및 머...,\n• 비정형화 된 데이터를 다양한 기술을 활용하여 팀원들에게 유의미한 정보로 만들...,NaN,https://www.wanted.co.kr/wd/97792,서울,데이터 사이언티스트
3,Data Scientist(데이터 사이언티스트),프라이데이즈랩(Retentics),폭풍 성장 중인 글로벌 스타트업에서 유저에게 사랑받는 리텐틱스를 만들기 위해 함께 ...,\n[데이터 사이언티스트로 이런 분을 찾아요]\n#자격 요건\n• 3년 이상의 ML...,\n[이런 경험이 있으신 분이면 더 좋아요]\n#우대 사항\n• Data Scien...,NaN,https://www.wanted.co.kr/wd/163313,서울,데이터 사이언티스트
4,데이터 사이언티스트,아템드메라키,Algorith는 데이터 및 통계수학적 분석을 통해 디지털 자산 투자 관리 회사입니...,"\n• 최소 데이터 과학, 통계, 컴퓨터 공학 또는 관련 분야의 학사 학위를 보유하...",\n• 석사학위 및 박사학위 (박사과정 지원자) 우대\n• 데이터 분석 또는 유사 ...,NaN,https://www.wanted.co.kr/wd/119383,서울,데이터 사이언티스트
...,...,...,...,...,...,...,...,...,...
128,MS-SQL 데이터베이스엔지니어,티디지,TDG는 Microsoft Cloud Solution Partner로서 풍부한 IT...,NaN,NaN,\nAzure\nC / C++\n개발\nSharePoint,https://www.wanted.co.kr/wd/171095,서울,데이터 엔지니어
129,공공기관 리눅스엔지니어(서버운영자),비욘드데이터,• 리눅스 엔지니어\n• 서버 운영\n주요업무\n• 서버 운영\n• 백업 & 보안S...,NaN,NaN,\nLinux\nOracle,https://www.wanted.co.kr/wd/171847,경북,데이터 엔지니어
130,리눅스엔지니어(중급/상주),비욘드데이터,• 서버 운영\n•\n주요업무\n• 리눅스 서버 관리\n•\n자격요건\n• 리눅스 ...,NaN,NaN,\nLinux\nOracle,https://www.wanted.co.kr/wd/172049,경북,데이터 엔지니어
131,"데이터엔지니어링/백엔드 개발자 (Python, Node.js)",코드크레인(CodeCrain),안녕하세요!\n저희 코드크레인은 국내에서 가장 빠르게 성장하고 있는 IT개발/컨설팅...,NaN,NaN,\nMySQL\nPython\nAWS\nNodeJS,https://www.wanted.co.kr/wd/160009,서울,데이터 엔지니어
132,[데이터사업] DB엔지니어,인젠트,"우리 모두를 위한 변화, 당신과 가장 가까운 인젠트의 스마트한 기술을 만나보세요.\...",NaN,NaN,\nLinux\n보안\n인프라\n정보 보안\nWindows 서버\n정보관리\nNAS...,https://www.wanted.co.kr/wd/112676,서울,데이터 엔지니어

In [4]:
wanted.to_csv(Task3_path + 'wanted.csv', index=False, encoding='utf-8-sig')
wanted = pd.read_csv(Task3_path + 'wanted.csv')
wanted

,Title,Company,Content,Requirement,Preference,StackTool,Link,Location,label
0,[100억↑투자] 데이터사이언티스트,해줌,"해줌은 2012년에 설립된 회사로, 소비자로부터 멀게만 느껴졌던 대한민국 태양광 산...",\n- 관련 업무 경력 3년 이상인 분\n- 시계열 데이터를 분석하여 예측에 대한 ...,\n- 기상관련 데이터 경험\n- 머신러닝 관련 모델링 도구 경험자 (Tensorf...,\nPytorch\nTensorflow\nPython,https://www.wanted.co.kr/wd/147049,서울,데이터 사이언티스트
1,데이터 사이언티스트,더블미디어,"더블미디어는 인터넷방송 플랫폼 ""팬더티비""을 서비스중입니다. 빠른 시간안에 국내에서...","\n•웹/앱 서비스 데이터 분석 경력 2년 이상, 혹은 그에 상응하는 업무 능력 보...",\n•통계 분석과 ML 알고리즘 지식과 실무 경험이 있으신 분\n\n•A/B 테스트...,\nKotlin\nSpring Framework,https://www.wanted.co.kr/wd/174955,서울,데이터 사이언티스트
2,플랫폼팀 데이터 사이언티스트,와이어드컴퍼니,[와이어드는 사람의 영향력을 가치로 바꿔갈 수 있는 동료를 찾고 있어요.]\n\n\...,\n• 커머스 관련 실무 경험을 2년 이상 가지고 계신 분\n• 데이터 분석 및 머...,\n• 비정형화 된 데이터를 다양한 기술을 활용하여 팀원들에게 유의미한 정보로 만들...,NaN,https://www.wanted.co.kr/wd/97792,서울,데이터 사이언티스트
3,Data Scientist(데이터 사이언티스트),프라이데이즈랩(Retentics),폭풍 성장 중인 글로벌 스타트업에서 유저에게 사랑받는 리텐틱스를 만들기 위해 함께 ...,\n[데이터 사이언티스트로 이런 분을 찾아요]\n#자격 요건\n• 3년 이상의 ML...,\n[이런 경험이 있으신 분이면 더 좋아요]\n#우대 사항\n• Data Scien...,NaN,https://www.wanted.co.kr/wd/163313,서울,데이터 사이언티스트
4,데이터 사이언티스트,아템드메라키,Algorith는 데이터 및 통계수학적 분석을 통해 디지털 자산 투자 관리 회사입니...,"\n• 최소 데이터 과학, 통계, 컴퓨터 공학 또는 관련 분야의 학사 학위를 보유하...",\n• 석사학위 및 박사학위 (박사과정 지원자) 우대\n• 데이터 분석 또는 유사 ...,NaN,https://www.wanted.co.kr/wd/119383,서울,데이터 사이언티스트
...,...,...,...,...,...,...,...,...,...
128,MS-SQL 데이터베이스엔지니어,티디지,TDG는 Microsoft Cloud Solution Partner로서 풍부한 IT...,NaN,NaN,\nAzure\nC / C++\n개발\nSharePoint,https://www.wanted.co.kr/wd/171095,서울,데이터 엔지니어
129,공공기관 리눅스엔지니어(서버운영자),비욘드데이터,• 리눅스 엔지니어\n• 서버 운영\n주요업무\n• 서버 운영\n• 백업 & 보안S...,NaN,NaN,\nLinux\nOracle,https://www.wanted.co.kr/wd/171847,경북,데이터 엔지니어
130,리눅스엔지니어(중급/상주),비욘드데이터,• 서버 운영\n•\n주요업무\n• 리눅스 서버 관리\n•\n자격요건\n• 리눅스 ...,NaN,NaN,\nLinux\nOracle,https://www.wanted.co.kr/wd/172049,경북,데이터 엔지니어
131,"데이터엔지니어링/백엔드 개발자 (Python, Node.js)",코드크레인(CodeCrain),안녕하세요!\n저희 코드크레인은 국내에서 가장 빠르게 성장하고 있는 IT개발/컨설팅...,NaN,NaN,\nMySQL\nPython\nAWS\nNodeJS,https://www.wanted.co.kr/wd/160009,서울,데이터 엔지니어
132,[데이터사업] DB엔지니어,인젠트,"우리 모두를 위한 변화, 당신과 가장 가까운 인젠트의 스마트한 기술을 만나보세요.\...",NaN,NaN,\nLinux\n보안\n인프라\n정보 보안\nWindows 서버\n정보관리\nNAS...,https://www.wanted.co.kr/wd/112676,서울,데이터 엔지니어

In [5]:
jobplanet.insert(3, 'Requirement', ds_j)
jobplanet.insert(4, 'Preference', da_j)
jobplanet.insert(5, 'StackTool', de_j)
jobplanet

,Title,Company,Content,Requirement,Preference,StackTool,Link,Location,label
0,Data-centric 기반 딥러닝 연구/개발 (Data Scientist),(주)에이모,상세\n리뷰\n면접\n요약\n마감일\n2023.10.31 상시채용\n직무\n데이터 ...,"\n- 관련 분야 경력 4년 이상이신 분\n- Computer vision, Ima...","\n- 관련 분야 석사/박사 학위 소지하신 분 (인공지능, 컴퓨터공학, 통계, 데이...","\npython, Docker, Tensorflow, Pytorch\n",https://www.jobplanet.co.kr/job/search?posting...,경기,데이터 사이언티스트
1,Data Scientist(데이터 사이언티스트),(주)프라이데이즈랩,상세\n리뷰\n면접\n요약\n마감일\n2023.11.01 상시채용\n직무\n데이터 ...,\n[데이터 사이언티스트로 이런 분을 찾아요]\n#\n• 3년 이상의 ML/DL 모...,\n[이런 경험이 있으신 분이면 더 좋아요]\n#우대 사항\n• Data Scien...,"\npython, 모델링, SQL, ml, dl\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
2,Data Scientist,(주)피에트,상세\n리뷰\n면접\n요약\n마감일\n2023.11.09 상시채용\n직무\n데이터 ...,"\n1. Data Science 관련 전공자 (통계, 수학, 컴퓨터공학, 산업공학 ...",\n1. 데이터 분석/모델링을 실제 서비스에 적용/개선한 경험이 있는 분\n2. 스...,"\n데이터분석, SQL, 파이썬, NLP\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
3,Data Scientist,(주)에이아이트릭스,상세\n리뷰\n면접\n요약\n마감일\n2023.10.11 상시채용\n직무\n데이터 ...,"\n• Data Science 관련(통계, 컴퓨터공학, 산업공학, 수학 등) 석사 ...",\n• 임상 통계관련 논문 보유자\n• 인공지능 및 머신러닝에 대한 이해도가 깊으신...,"\n데이터분석, SQL, 파이썬, NLP\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
4,"Senior Data Scientist, Core",(주)몰로코,상세\n리뷰\n면접\n요약\n마감일\n2023.08.22 D-11 (채용시 마감)\...,\n• Master's degree in a quantitative discipli...,\n• PhD degree in a quantitative discipline.\n...,"\n데이터분석, python, SQL, R, 머신러닝, 데이터 분석, 파이썬, 딥러...",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
...,...,...,...,...,...,...,...,...,...
73,Data Engineer (Digital Biomarker),웰트(주),상세\n리뷰\n면접\n요약\n마감일\n2023.08.17 상시채용\n직무\n데이터 ...,"\n• 백앤드 개발 언어(Go, Python) 중 하나 이상 능숙하게 구사할 수 있...",\n• 오픈소스 컨트리뷰터 혹은 메인테이너\n• 딥러닝 연구나 이를 활용한 서비스 ...,"\npython, SQL, 백엔드, go\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 엔지니어
74,데이터 플랫폼 엔지니어,(주)피플펀드컴퍼니,상세\n리뷰\n면접\n요약\n마감일\n2023.10.19 상시채용\n직무\n데이터 ...,\n• 5년 이상 10년 이하의 클라우드 기반 데이터 플랫폼 구축 및 운영에 익숙한...,"\n• AWS와 AWS의 서비스(GLUE, EMR, EKS, Redshift)를 다...","\nios, kotlin, python, MYSQL, hadoop, Spark\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 엔지니어
75,Cloud Data Platform Engineer,(주)케이티넥스알,상세\n리뷰\n면접\n요약\n마감일\n2023.11.28 상시채용\n직무\n데이터 ...,\n• 3년 이상(석/박사 학위 기간 포함) 경력 보유\n• Linux / UNIX...,\n• Kubernetes 구축/운영 경험 보유\n• Linux container ...,"\nLinux, hadoop, unix, Spark, Docker\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 엔지니어
76,Data Engineer (데이터 엔지니어),지엔터프라이즈(주),상세\n리뷰\n면접\n요약\n마감일\n2023.09.20 상시채용\n직무\n데이터 ...,\n• 웹스퀘어 기반 사이트 스크래핑 업무 경험(홈택스 등)\n• 데이터 엔지니어링...,\n• AWS 등 클라우드 기반 데이터 플랫폼 구축 및 워크플로우 운영 경험이 있으...,"\npython, aws, 데이터 분석, node.js, Flask, nestjs\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 엔지니어
77,Data Engineer (3년 이상),버즈앤비(주),상세\n리뷰\n면접\n요약\n마감일\n2023.08.16 상시채용\n직무\n데이터 ...,\n- 유관 경력 2년 이상 혹은 그에 준하는 실력을 지니신 분\n- 모바일 앱서비...,"\n- AWS, GCP 클라우드 환경에 대한 이해와 경험 보유한 분\n- Docke...","\npm, aws, git, Docker, 데이터엔지니어, gcp\n",https://www.jobplanet.co.kr/job/search?posting...,경기,데이터 엔지니어

In [6]:
df = pd.concat([wanted, jobplanet])
df.reset_index(drop=True, inplace=True)
sorted_df = df.sort_values('label')
sorted_df.reset_index(drop=True, inplace=True)
sorted_df

,Title,Company,Content,Requirement,Preference,StackTool,Link,Location,label
0,[100억↑투자] 데이터사이언티스트,해줌,"해줌은 2012년에 설립된 회사로, 소비자로부터 멀게만 느껴졌던 대한민국 태양광 산...",\n- 관련 업무 경력 3년 이상인 분\n- 시계열 데이터를 분석하여 예측에 대한 ...,\n- 기상관련 데이터 경험\n- 머신러닝 관련 모델링 도구 경험자 (Tensorf...,\nPytorch\nTensorflow\nPython,https://www.wanted.co.kr/wd/147049,서울,데이터 사이언티스트
1,Data Scientist,(주)데이터라이즈,상세\n리뷰\n면접\n요약\n마감일\n2023.08.31 상시채용\n직무\n데이터 ...,\n• 3년 이상의 데이터 모델링/분석 혹은 서빙 시스템 개발 경력이 있거나 그에 ...,\n• 기술 트렌드에 관심이 있고 지속적으로 학습하는 분\n• 새로운 도메인 지식을...,"\npython, SQL, 머신러닝, 알고리즘\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
2,Data Scientist,(주)케이티넥스알,상세\n리뷰\n면접\n요약\n마감일\n2023.08.31 상시채용\n직무\n데이터 ...,\n• Python을 이용한 Data Analysis Process 수행 가능자 (...,\n• Deep Learning 프로젝트 수행 가능자\n• 석/박사 학위자\n• 관...,"\njava, 데이터분석, R, hadoop, 파이썬\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
3,Senior Data Scientist (Senior Data Scientist),(주)크로커스,상세\n리뷰\n면접\n요약\n마감일\n2023.08.17 상시채용\n직무\n데이터 ...,\n• AI 관련 학위 또는 실무 경험 7년 이상 (석/박사 경력 인정)\n• 머신...,"\n• 전자전기 및 에너지 도메인에 대한 이해도가 높고, 경험이 있으신 분\n• 머...","\n연구개발, AI, 데이터분석, 머신러닝, 데이터사이언티스트\n",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
4,"Senior Data Scientist, Core",(주)몰로코,상세\n리뷰\n면접\n요약\n마감일\n2023.08.22 D-11 (채용시 마감)\...,\n• Master's degree in a quantitative discipli...,\n• PhD degree in a quantitative discipline.\n...,"\n데이터분석, python, SQL, R, 머신러닝, 데이터 분석, 파이썬, 딥러...",https://www.jobplanet.co.kr/job/search?posting...,서울,데이터 사이언티스트
...,...,...,...,...,...,...,...,...,...
206,데이터 엔지니어,빅쏠,"혜택이 늘어나는 카드 소비 생활 앱 ""더쎈카드""의 데이터 엔지니어를 모십니다.\n\...",\n[이런 분이 우리 크루였으면 좋겠어요]\n• 빅데이터 엔지니어링 관련 개발 경...,"\n[이런 분이면 바로 지원하시는 걸 추천해요]\n• Spark, Kafka 및 K...",\nGit\nLinux\nMySQL\nRedis\nJava\nPython\nSQL\...,https://www.wanted.co.kr/wd/173121,서울,데이터 엔지니어
207,데이터 엔지니어,롯데헬스케어,"""Every Moment of your Healthy Life""\n\n롯데헬스케어는...",\n• Data Engineer 실무 경력 3년 이상이신 분\n• 데이터 처리를 위...,"\n• A/B Test, 광고 플랫폼, 분석 시각화 관련 업무 경험 보유한 분\n•...",\nGithub\nAzure\nKotlin\nPython\nAWS\nJenkins\...,https://www.wanted.co.kr/wd/143597,서울,데이터 엔지니어
208,[플랫폼 개발] 빅데이터 시스템 엔지니어,피플앤드테크놀러지,Industry 4.0의 파도를 함께 타고 항해 하실 마케터 모십니다. \n\n[피...,"\n• 컴퓨터 공학적 지식에 익숙하신 분\n• Hadoop, Spark 와 같은 분...",\n• 학술 데이터 관련 업무 수행\n• 논문 작성 및 연구 경험\n• 데이터베이스...,NaN,https://www.wanted.co.kr/wd/79517,서울,데이터 엔지니어
209,데이터 엔지니어,씨제이대한통운(CJ대한통운),국내 1위 물류업계 CJ대한통운에서 \n지속적으로 수집된 물류 데이터(데이터 약 1...,\n학력 : 초대졸이상\n데이터베이스 운영 및 관리 경력 2년 이상\n데이터베이스 ...,\n- 클러스터 고가용서 유경험자\n- 관련 학과 전공자\n- 관련 자격증 보유자\n,\nGitLab\nCSS\nTypeScript\nReact.js\nNext.js,https://www.wanted.co.kr/wd/157213,서울,데이터 엔지니어
210,Data Engineer (3년 이상),버즈앤비(주),상세\n리뷰\n면접\n요약\n마감일\n2023.08.16 상시채용\n직무\n데이터 ...,\n- 유관 경력 2년 이상 혹은 그에 준하는 실력을 지니신 분\n- 모바일 앱서비...,"\n- AWS, GCP 클라우드 환경에 대한 이해와 경험 보유한 분\n- Docke...","\npm, aws, git, Docker, 데이터엔지니어, gcp\n",https://www.jobplanet.co.kr/job/search?posting...,경기,데이터 엔지니어

In [7]:
sorted_df.to_csv('C:\\VSC\\JJaemni\\CSV\\wanted_jobplanet.csv', index=False, encoding='utf-8-sig')